//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachment
    {
        public int ID { get; set; }
        public int PlanID { get; set; }
        public Nullable<int> BucketID { get; set; }
        public Nullable<int> TaskID { get; set; }
        public Nullable<int> CommentID { get; set; }
        public string Reporter { get; set; }
        public string Attachment1 { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Bucket Bucket { get; set; }
        public virtual Comment Comment { get; set; }
        public virtual Plan Plan { get; set; }
        public virtual task task { get; set; }
    }
}
