//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListMember
    {
        public int ID { get; set; }
        public string AccountID { get; set; }
        public int PlanID { get; set; }
        public bool RoleProject { get; set; }
        public System.DateTime DateJoined { get; set; }
        public System.DateTime DateLeft { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Plan Plan { get; set; }
    }
}
